import "./globals.css";
import Header from "./header";
import Footer from "./footer";
import { getDictionary } from "@/app/lib/i18n/getDictionary";
import { cookies } from "next/headers";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const lang = cookieStore.get("lang")?.value || "en";
  const dict = await getDictionary(lang);

  return (
    <html lang={lang}>
      <head>
        <title>vloerplaat</title>
      </head>
      <body>
        <Header dict={dict} lang={lang} />
        <main>{children}</main>
        <Footer dict={dict} />
      </body>

      {/* <script defer src="https://app.fastbots.ai/embed.js" data-bot-id="cmmk8igxz02d1pb1pwdjnbf2e"></script> */}
      <Script
        src="https://app.fastbots.ai/embed.js"
        strategy="afterInteractive"
        data-bot-id="cmmk8igxz02d1pb1pwdjnbf2e"
      />
    </html>
  );
}
